package com.apt.entity;
// Generated Mar 23, 2016 6:49:46 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Batch generated by hbm2java
 */
@Entity
@Table(name="batch"
    ,catalog="supportivelearning"
    , uniqueConstraints = @UniqueConstraint(columnNames="BatchName") 
)
public class Batch  implements java.io.Serializable {


     private Integer batchId;
     private String batchName;
     private Set<Student> students = new HashSet<Student>(0);
     private Set<Assignment> assignments = new HashSet<Assignment>(0);

    public Batch() {
    }

	
    public Batch(String batchName) {
        this.batchName = batchName;
    }
    public Batch(String batchName, Set<Student> students, Set<Assignment> assignments) {
       this.batchName = batchName;
       this.students = students;
       this.assignments = assignments;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="BatchID", unique=true, nullable=false)
    public Integer getBatchId() {
        return this.batchId;
    }
    
    public void setBatchId(Integer batchId) {
        this.batchId = batchId;
    }

    
    @Column(name="BatchName", unique=true, nullable=false, length=50)
    public String getBatchName() {
        return this.batchName;
    }
    
    public void setBatchName(String batchName) {
        this.batchName = batchName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="batch")
    public Set<Student> getStudents() {
        return this.students;
    }
    
    public void setStudents(Set<Student> students) {
        this.students = students;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="batch")
    public Set<Assignment> getAssignments() {
        return this.assignments;
    }
    
    public void setAssignments(Set<Assignment> assignments) {
        this.assignments = assignments;
    }




}


