package com.apt.entity;
// Generated Mar 23, 2016 6:49:46 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name="student"
    ,catalog="supportivelearning"
)
public class Student  implements java.io.Serializable {


     private Integer studentId;
     private Batch batch;
     private String studentName;
     private String password;
     private Set<Submit> submits = new HashSet<Submit>(0);

    public Student() {
    }

	
    public Student(Batch batch, String studentName) {
        this.batch = batch;
        this.studentName = studentName;
    }
    public Student(Batch batch, String studentName, String password, Set<Submit> submits) {
       this.batch = batch;
       this.studentName = studentName;
       this.password = password;
       this.submits = submits;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="StudentID", unique=true, nullable=false)
    public Integer getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="BatchID")
    public Batch getBatch() {
        return this.batch;
    }
    
    public void setBatch(Batch batch) {
        this.batch = batch;
    }

    
    @Column(name="StudentName", nullable=false, length=50)
    public String getStudentName() {
        return this.studentName;
    }
    
    public void setStudentName(String studentName) {
        this.studentName = studentName;
    }

    
    @Column(name="Password", length=32)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="student")
    public Set<Submit> getSubmits() {
        return this.submits;
    }
    
    public void setSubmits(Set<Submit> submits) {
        this.submits = submits;
    }




}


