package com.apt.entity;
// Generated Mar 23, 2016 6:49:46 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Subject generated by hbm2java
 */
@Entity
@Table(name="subject"
    ,catalog="supportivelearning"
    , uniqueConstraints = @UniqueConstraint(columnNames="SubjectName") 
)
public class Subject  implements java.io.Serializable {


     private Integer subjectId;
     private String subjectName;
     private Set<Assignment> assignments = new HashSet<Assignment>(0);

    public Subject() {
    }

	
    public Subject(String subjectName) {
        this.subjectName = subjectName;
    }
    public Subject(String subjectName, Set<Assignment> assignments) {
       this.subjectName = subjectName;
       this.assignments = assignments;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="SubjectID", unique=true, nullable=false)
    public Integer getSubjectId() {
        return this.subjectId;
    }
    
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }

    
    @Column(name="SubjectName", unique=true, nullable=false, length=50)
    public String getSubjectName() {
        return this.subjectName;
    }
    
    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subject")
    public Set<Assignment> getAssignments() {
        return this.assignments;
    }
    
    public void setAssignments(Set<Assignment> assignments) {
        this.assignments = assignments;
    }




}


